# Generated by Django 5.2.7 on 2025-12-16 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_category_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
