# Generated by Django 5.2.7 on 2026-07-21 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_alter_category_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginMFACode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_mfa_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Login MFA Code',
                'verbose_name_plural': 'Login MFA Codes',
                'ordering': ['-created_at'],
            },
        ),
    ]
